---
Book Value (Rs): book_value
Networth: net_worth
"Less: Accum. Depreciation": accumulated_depreciation
Miscellaneous Expenses: misc_expenses
Book Value (Rs): book_value
Other Liabilities & Provisions: other_liabilities
Cash & Balances with RBI: balance_with_rbi
Balance with Banks, Money at Call: money_at_call
Capital Work in Progress: capital_work_in_progress
Loans and Advances: loans_and_advances
Deffered Credit: deferred_credit
Cash and Bank Balance: cash_and_bank_balance
Bills for collection: bills_for_collection
Profit On Sale Of Assets: profit_on_assets_sale
Profit On Sale Of Investments: profit_on_investments_sale
Gain/Loss On Foreign Exchange: profit_on_forex
Other Extraordinary Income/Expenses: other_extraordinary_income
Total Extraordinary Income/Expenses: total_extraordinary_income
Tax On Extraordinary Items: tax_on_extraordinary_income
Net Extra Ordinary Income/Expenses: net_extraordinary_income
Depreciation On Revaluation Of Assets: depreciation_on_revaluated_assets
Prior Years Income/Expenses: prior_years_income
Depreciation for Previous Years Written Back/ Provided: depreciation_for_previous_years
Dividend (%): dividend_percentage
Earnings Per Share: eps
Power & Fuel Cost: power_and_fuel_cost
Miscellaneous Expenses: misc_expenses
Preoperative Exp Capitalised: preoperative_capex
Extra-ordinary items: extraordinary_items
Reported Net Profit: net_profit
Corporate Dividend Tax: dividend_tax
Shares in issue (lakhs): issued_shares
Earning Per Share (Rs): eps
Equity Dividend (%): dividend_percentage
Book Value (Rs): book_value
Selling and Admin Expenses: sales_and_admin_expenses
Profit Before Tax: pbt